/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Obnj43HBlPV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { JSX, SVGProps } from "react"

export function dashboard() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-muted/40">
      <main className="flex-1 grid gap-4 p-4 sm:px-6 sm:py-0 md:gap-8">
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 mt-20">
          <Card className="col-span-2 lg:col-span-1">
            <CardHeader>
              <CardTitle>Quick Actions</CardTitle>
            </CardHeader>
            <CardContent className="flex items-center justify-center">
             <Link href={'/jurney'}> <Button className="w-full max-w-[200px] bg-orange-500 hover:bg-orange-600 text-primary-foreground">Create Itinerary +</Button></Link>
            </CardContent>
          </Card>
          <Card className="col-span-2 lg:col-span-2">
            <CardHeader>
              <CardTitle>Upcoming Itineraries</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <Link
                  href="#"
                  className="flex items-center gap-4 rounded-md bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  <div className="flex-1">
                    <div className="text-sm font-medium">Monsoon Getaway</div>
                    <div className="text-xs text-muted-foreground">Munnar, Kerala - July 10-15</div>
                  </div>
                  <div className="text-sm font-medium">
                    <ChevronRightIcon className="h-5 w-5" />
                  </div>
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-4 rounded-md bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  <div className="flex-1">
                    <div className="text-sm font-medium">Heritage Tour</div>
                    <div className="text-xs text-muted-foreground">Jaipur, Rajasthan - September 20-22</div>
                  </div>
                  <div className="text-sm font-medium">
                    <ChevronRightIcon className="h-5 w-5" />
                  </div>
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-4 rounded-md bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  <div className="flex-1">
                    <div className="text-sm font-medium">Beach Escape</div>
                    <div className="text-xs text-muted-foreground">Goa - December 15-22</div>
                  </div>
                  <div className="flex items-center gap-4 rounded-md p-4 transition-colors hover:bg-accent hover:text-accent-foreground">
                    <div className="text-sm font-medium">
                      <ChevronRightIcon className="h-5 w-5" />
                    </div>
                  </div>
                </Link>
              </div>
            </CardContent>
          </Card>
          <Card className="col-span-2 lg:col-span-1">
            <CardHeader>
              <CardTitle>Recommendations</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <Link
                  href="#"
                  className="grid grid-cols-[100px_1fr] items-center gap-4 rounded-md bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  <img
                    src="/udaipur.jpg"
                    width={100}
                    height={100}
                    alt="Destination"
                    className="aspect-square rounded-md object-cover"
                  />
                  <div>
                    <div className="text-sm font-medium">Udaipur, Rajasthan</div>
                    <div className="text-xs text-muted-foreground">
                    Explore the City of Lakes and its royal heritage
                    </div>
                  </div>
                </Link>
                <Link
                  href="#"
                  className="grid grid-cols-[100px_1fr] items-center gap-4 rounded-md bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  <img
                    src="/concert.jpg"
                    width={100}
                    height={100}
                    alt="Event"
                    className="aspect-square rounded-md object-cover"
                  />
                  <div>
                    <div className="text-sm font-medium">Coachella Music Festival</div>
                    <div className="text-xs text-muted-foreground">Experience the best in music, art, and culture.</div>
                  </div>
                </Link>
                <Link
                  href="#"
                  className="grid grid-cols-[100px_1fr] items-center gap-4 rounded-md bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}
                >
                  <img
                    src="/andaman.jpg"
                    width={100}
                    height={100}
                    alt="Destination"
                    className="aspect-square rounded-md object-cover"
                  />
                  <div>
                    <div className="text-sm font-medium">Andaman and Nicobar Islands</div>
                    <div className="text-xs text-muted-foreground">
                    Discover pristine beaches and lush rainforests.
                    </div>
                  </div>
                </Link>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}

function ChevronRightIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
