/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/b5XpPdsntsQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function signup() {
  return (
    <Card className="mx-auto max-w-sm">
      <CardHeader>
        <CardTitle className="text-xl">Join Travela and Start Your Adventure!</CardTitle>
        <CardDescription>Enter your details to create a travel account.</CardDescription>
      </CardHeader>
      <CardContent>
        <div className="grid gap-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="grid gap-2">
              <Label htmlFor="first-name">First Name</Label>
              <Input id="first-name" placeholder="Hobby" required />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="last-name">Last Name</Label>
              <Input id="last-name" placeholder="Explorer" required />
            </div>
          </div>
          <div className="grid gap-2">
            <Label htmlFor="email">Email </Label>
            <Input id="email" type="email" placeholder="adventure@example.com" required />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="password">Create a password</Label>
            <Input id="password" type="password" />
          </div>
          <Link href={'/pip'}>
          <Button type="submit" className="w-full bg-orange-500 hover:orange">
          Create Account and Begin Journey
          </Button>
          </Link>
          <Button variant="outline" className="w-full border-orange-500 border-2 text-orange-500">
          Sign Up with Google for a Quick Start
          </Button>
        </div>
        <div className="mt-4 text-center text-sm">
        Already a traveler?{" "}
          <Link href={'/login'} className="underline" prefetch={false}>
            Sign in
          </Link>
        </div>
      </CardContent>
    </Card>
  )
}
